### ISSUE TITLE
-query-k8s, -include-unqualified option(s) require RBAC permissions

### ISSUE THREAD

**Issue by fred-vogt** [proofpoint/certificate-init-container#33]
Specifically `get,list` are needed for `pods, services` in the default API group when using these options:
```yaml
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
```
Consider adding this to the README.

kube apiserver logs:
```
Could not query pod "<pod>" in namespace "<namespace>": 
  pods "<pod>" is forbidden: 
  User "system:serviceaccount:kube-system:<name>" 
  cannot get resource "pods" in API group "" in the namespace "<namespace>"
```
